run on pull_request

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,7 +1,7 @@
 name: CI
 
 on:
-  push:
+  pull_request:
     branches:
       - main
 
@@ -11,7 +11,7 @@ jobs:
 
     steps:
     - name: Checkout Repository
-      uses: actions/checkout@v2
+      uses: actions/checkout@v3
 
     - name: Debug
       run: |
@@ -26,4 +26,18 @@ jobs:
       run: npm install
 
     - name: Run Tests
-      run: npm test
+      run: |
+        test_output=$(npm test)
+        # Check if the output contains a specific string or pattern
+        if [[ ! $test_output == *"failed"* ]]; then
+          echo "Tests passed successfully"
+        else
+          echo "Tests failed or produced unexpected output"
+          exit 1
+        fi
+        if [[ $? -eq 0 ]]; then
+          echo "Output check passed"
+        else
+          echo "Output check failed"
+          exit 1
+        fi        
