added if/else

diff --git a/.github/workflows/merge_group.yml b/.github/workflows/merge_group.yml
--- a/.github/workflows/merge_group.yml
+++ b/.github/workflows/merge_group.yml
@@ -25,5 +25,10 @@ jobs:
       run: |
         chmod +x increment_version.sh
         ./increment_version.sh
-        git status
-        exit $?
+        git_Status=(git status)
+        if [[ $git_Status -eq 0  ]]; then
+          echo "Tests passed successfully"
+        else
+          echo "Tests failed or produced unexpected output"
+          exit 1
+        fi
